#port => 저장하지 않는 경우 : 8080 => 9090 : ufw = > 포트 허용
#MVC => SpringFramework와 동일
spring:
 mvc:
  view:
   prefix: /WEB-INF/views/
   suffix: .jsp
 datasource:
  url: jdbc:oracle:thin:@//211.238.142.22:1521/XE
  username: sist2
  password: happy
  driver-class-name: oracle.jdbc.OracleDriver
  type: com.zaxxer.hikari.HikariDataSource
  hikari: 
   minimum-idle: 5
   maximum-pool-size: 10
   idle-timeout: 3000
   max-lifetime: 1800000
   connection-timeout: 30000
 security:
     oauth2:
       client:
         registration:
           kakao:
             client-id: dbda976eb054714809926c699703fc3b
             client-secret: IKdsMnzh7RZtKoub161cFADP8ASc6pml
             authorization-grant-type: authorization_code
             client-authentication-method: client_secret_post
             redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
             client-name: Kakao
           naver:
             client-id: 0hXy2isjmPP_8MICXjsZ
             client-secret: lpMGBLOWuv
             authorization-grant-type: authorization_code
             redirect-uri: "{baseUrl}/login/oauth2/code/naver"
             client-name: Naver
         provider:
           kakao:
             authorization-uri: https://kauth.kakao.com/oauth/authorize
             token-uri: https://kauth.kakao.com/oauth/token
             user-info-uri: https://kapi.kakao.com/v2/user/me
             user-name-attribute: id
           naver:
             authorization-uri: https://nid.naver.com/oauth2.0/authorize
             token-uri: https://nid.naver.com/oauth2.0/token
             user-info-uri: https://openapi.naver.com/v1/nid/me
             user-name-attribute: response # 네이버는 response 키 안에 정보가 있음
#mybatis
mybatis:
 type-aliases-package: com.sist.web.vo
 mapper-locations: mybatis/mapper/*.xml
#JPA
#Security
#WebSocket
#MSA
file:
  upload-dir: c:/bootDev/bootStudy/images/
---

spring:
  config:
    activate:
      on-profile: prod
file:
  upload-dir: /home/ubuntu/app/images/